[package]
name = "cgolrs"
version = "0.0.0"
edition = "2024"

[dependencies]
rand = "0.9.2"
getopts = "0.2.24"
regex = "1.12.2"
crossterm = "0.29.0"
rayon = "1.10.0"

[profile.release]
debug = true
lto = true
